name: Terraform Deploy to Azure

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'
  pull_request:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.6

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        auth-type: OIDC

    - name: Generate .tfvars dynamically
      run: |
        cat <<EOF > terraform.tfvars
        resource_group_name = "WebApp3TierRG"
        location            = "East US"

        tags = {
          environment = "dev"
          owner       = "mark.joshua"
        }

        vnet_name          = "WebApp3Tier_Vnet"
        vnet_address_space = ["10.0.0.0/16"]

        subnets = {
          Bastion = {
            address_prefixes = ["10.0.1.0/24"]
          }
          ApplicationGatewaySubnet = {
            address_prefixes = ["10.0.2.0/24"]
          }
          DBSubnet = {
            address_prefixes = ["10.0.3.0/24"]
          }
          AppSubnet = {
            address_prefixes = ["10.0.4.0/24"]
          }
          WebSubnet = {
            address_prefixes = ["10.0.5.0/24"]
          }
        }
        EOF

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -var-file="terraform.tfvars"

    - name: Terraform Destroy (auto-approve)
      if: github.ref == 'refs/heads/main'
      run: terraform destroy -auto-approve -var-file="terraform.tfvars"
